### PR TITLE
Font autoconfigure

### PR DESCRIPTION
**Pull request by dkochmanski**
Refactor CLX fonts and TTF extension

### CODE REVIEW

**Comment by jorams** [comment]
There is another library, [clx-truetype](https://github.com/filonenko-mikhail/clx-truetype), that does antialiased TTF font rendering for CLX. Was this looked at?

Rendering using that library tends to perform terribly, so I wonder how the implementation here compares.

**Comment by stacksmith** [comment]
dkochmanski: 
I may be doing something stupid, but I checked out your branch to take a look.  Loading via (ql:quickload :mcclim) craps out (sbcl 1.3.8):
````
The name "ALEXANDRIA" does not designate any package.
   [Condition of type SB-KERNEL:SIMPLE-PACKAGE-ERROR]

Restarts:
 0: [TRY-RECOMPILING] Recompile package and try loading it again
 1: [RETRY] Retry loading FASL for #<CL-SOURCE-FILE "clim-lisp" "package">.
 2: [ACCEPT] Continue, treating loading FASL for #<CL-SOURCE-FILE "clim-lisp" "package"> as having been successful.
 3: [RETRY] Retry ASDF operation.
 4: [CLEAR-CONFIGURATION-AND-RETRY] Retry ASDF operation after resetting the configuration.
 5: [ABORT] Give up on "mcclim"
 --more--

Backtrace:
  0: (SB-INT:FIND-UNDELETED-PACKAGE-OR-LOSE "ALEXANDRIA")
  1: (SB-IMPL::IMPORT-LIST-SYMBOLS (("ALEXANDRIA" "ENSURE-GETHASH")))
  2: ((FLET SB-IMPL::THUNK :IN SB-IMPL::%DEFPACKAGE))
  3: ((FLET #:WITHOUT-INTERRUPTS-BODY-387 :IN SB-THREAD::CALL-WITH-RECURSIVE-LOCK))
  4: (SB-THREAD::CALL-WITH-RECURSIVE-LOCK #<CLOSURE (FLET SB-THREAD::WITH-RECURSIVE-LOCK-THUNK :IN SB-IMPL::CALL-WITH-PACKAGE-GRAPH) {7FFFE4244B1B}> #<SB-THREAD:MUTEX "Package Graph Lock" owner: #<SB-THREA..
  5: (SB-IMPL::CALL-WITH-PACKAGE-GRAPH #<CLOSURE (FLET SB-IMPL::THUNK :IN SB-IMPL::%DEFPACKAGE) {7FFFE4244B6B}>)
  6: (SB-IMPL::%DEFPACKAGE "CLIM-INTERNALS" ("CLIMI") NIL NIL NIL ("CLIM" "CLIM-SYS" "CLIM-EXTENSIONS" "CLIM-BACKEND" "CLIM-LISP") (("ALEXANDRIA" "ENSURE-GETHASH")) ("LETF") NIL ("CLIM-INTERNALS") NIL NIL ..
  7: (SB-FASL::LOAD-FASL-GROUP #S(SB-FASL::FASL-INPUT :STREAM #<SB-SYS:FD-STREAM for "file /home/stacksmith/.cache/common-lisp/sbcl-1.3.8-linux-x64/home/stacksmith/2016/lisp/McCLIM/package.fasl" {100DDE958..
  8: (SB-FASL::LOAD-AS-FASL #<SB-SYS:FD-STREAM for "file /home/stacksmith/.cache/common-lisp/sbcl-1.3.8-linux-x64/home/stacksmith/2016/lisp/McCLIM/package.fasl" {100DDE9583}> NIL NIL)
  9: ((FLET SB-FASL::LOAD-STREAM :IN LOAD) #<SB-SYS:FD-STREAM for "file /home/stacksmith/.cache/common-lisp/sbcl-1.3.8-linux-x64/home/stacksmith/2016/lisp/McCLIM/package.fasl" {100DDE9583}> T)
 10: (LOAD #P"/home/stacksmith/.cache/common-lisp/sbcl-1.3.8-linux-x64/home/stacksmith/2016/lisp/McCLIM/package.fasl" :VERBOSE NIL :PRINT NIL :IF-DOES-NOT-EXIST T :EXTERNAL-FORMAT :DEFAULT)
 11: (UIOP/UTILITY:CALL-WITH-MUFFLED-CONDITIONS #<CLOSURE (LAMBDA NIL :IN UIOP/LISP-BUILD:LOAD*) {100DDE716B}> ("Overwriting already existing readtable ~S." #(#:FINALIZERS-OFF-WARNING :ASDF-FINALIZERS)))
 12: ((SB-PCL::EMF ASDF/ACTION:PERFORM) #<unavailable argument> #<unavailable argument> #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "clim-lisp" "package">)
 13: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS (ASDF/LISP-ACTION:LOAD-OP ASDF/LISP-ACTION:CL-SOURCE-FILE)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "clim-lisp" "package">) [fast-met..
 14: ((:METHOD ASDF/ACTION:PERFORM-WITH-RESTARTS :AROUND (T T)) #<ASDF/LISP-ACTION:LOAD-OP > #<ASDF/LISP-ACTION:CL-SOURCE-FILE "clim-lisp" "package">) [fast-method]
 15: ((:METHOD ASDF/PLAN:PERFORM-PLAN (LIST)) ((#1=#<ASDF/LISP-ACTION:PREPARE-OP > . #2=#<ASDF/SYSTEM:SYSTEM #3="trivial-gray-streams">) (#1# . #4=#<ASDF/LISP-ACTION:CL-SOURCE-FILE #3# "package">) (#5=#<AS..
 16: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
 17: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) ((#1=#<ASDF/LISP-ACTION:PREPARE-OP > . #2=#<ASDF/SYSTEM:SYSTEM #3="trivial-gray-streams">) (#1# . #4=#<ASDF/LISP-ACTION:CL-SOURCE-FILE #3# "package">) (#5..
 18: ((FLET SB-C::WITH-IT :IN SB-C::%WITH-COMPILATION-UNIT))
 19: ((:METHOD ASDF/PLAN:PERFORM-PLAN :AROUND (T)) #<ASDF/PLAN:SEQUENTIAL-PLAN {100AB45593}> :VERBOSE NIL) [fast-method]
 --more--
````

**Comment by TeMPOraL** [comment]
Looks to me that Alexandria is referenced in package.lisp in an `:import-from: clause, but it's not included anywhere, in particular in `:depends-on` clause in the mcclim.asd file.

**Comment by dkochmanski** [comment]
yes, that was me being sloppy, thanks! (last commit fixes this)

**Comment by dkochmanski** [comment]
@jorams I wasn't aware about that, will check it for sure. Thanks.

**Comment by stacksmith** [comment]
jorams, dkochmanski - it seems that neither McCLIM nor clx-truetype render fonts using sub-pixel antialiasing that makes all the difference visually:
[here](https://img42.com/tquph)
I am trying to figure it out... xrender should support it.

**Comment by dkochmanski** [comment]
XRender is an extension which we use to draw fonts ourself (using cl-vectors etc.).

Excerpt from the McCLIM truetype extension readme:

### TODO

* Kerning (we didn't do this with Freetype, either. Oops.)
* Implement fixed-font-width-p for zpb-ttf.
* Boxes for missing glyphs.
* Make certain left/right bearings and text-bounding-rectangle are
  correct. (I doubt they are..)

### Wish-list

* Subpixel antialiasing. It would be straightforward to generate the
  glyphs by tripling the width as passed to cl-vectors and compressing
  triplets of pixels together ourselves. I'm not certain how to draw
  the result through xrender. I've seen hints on Google that there is
  subpixel AA support in xrender, which isn't obvious from CLX or the 
  spec. Failing that, we could use a 24bpp mask with component-alpha. 
  That might even be how you're supposed to do it. I'm skeptical as to 
  whether this would be accelerated for most people.

* Subpixel positioning. Not hard in principle - render multiple versions
  of each glyph, offset by fractions of a pixel. Horizontal positioning
  is more important than vertical, so 1/4 pixel horizontal resolution
  and 1 pixel vertical resolution should suffice. Given how ugly most
  CLIM apps are, and the lack of WYSIWYG document editors crying out 
  for perfect text spacing in small fonts, we don't really need this.

**Pull request merged**
