### PR TITLE
set max-width/height to +fill+

### PR DESCRIPTION
**Pull request by gas2serra**
Issue #144.

PS: The look and feel of several apps changes.

### CODE REVIEW

**Comment by dkochmanski** [comment]
I wonder myself whenever max-height should be always `+fill+` – that definetely depends on the gadget.

For instance, taking example from material.io, button height is fixed (unit is dp), see:
https://material.io/guidelines/components/buttons.html#buttons-style

**Comment by dkochmanski** [comment]
what is arguably the right thing- then button is always a button, if someone wants to have "touchable pane", then a new gadget may be created.

**Comment by dkochmanski** [comment]
using fixed sizes (in dp so it looks good on different kind of screens) would make our life easier I think (this isn't the right place to discuss it, just thinking out lould)

**Comment by gas2serra** [comment]
> that definetely depends on the gadget.
Yes.
> using fixed sizes (in dp so it looks good on different kind of screens) would make our life easier
I agree. 

The problem is that user cannot change it.
If we use +fill+ the user has more freedom.

If the user want be conservative her can use:
` :max-width '(1.0 :point :relative)` 
or adding +fill+ in the container.

**Comment by dkochmanski** [comment]
If we implement material design it is up to implementer to provide "fixed" values for this style.

**Pull request merged**
