### PR TITLE
better support for multiprocessing

### PR DESCRIPTION
**Pull request by ailisp**
1. Add support for without-scheduling, enable/disable/restart process, atomic-incf and atomic-decf.
2. Change process-state, process-whostate to support running, waiting, disabled state. And we can know waiting reason now from whostate.
3. Fix some trivial on locks to better obey CLIM II Spec.
4. All has been tested under SBCL 1.3.1-debian. Only apis suggested by bordeaux-threads which is said to work uniformly under different implementations are used, so other platforms should also work.

### CODE REVIEW

**Comment by ailisp** [comment]
This is my test code, if load by c-c c-k, need to use the SHADOW-IMPORT restart to use symbol in clim-sys:
```
(clim-sys:current-process)

(clim-sys:all-processes)

(defparameter *a* nil)
(defparameter *b* nil)
(defparameter *a-lock* (clim-sys:make-lock "lock for *a*"))
(defun test-mp ()
  (let ((p1 (clim-sys:make-process
	     #'(lambda ()
		 (loop
		    (clim-sys:with-lock-held (*a-lock*)
		      (push (random 1) *a*))
		    (sleep 1)
		    (clim-sys:with-lock-held (*a-lock*)
		      (push (clim-sys:current-process) *a*))
		    (sleep 2)))
	     :name "process 1"))
	(p2 (clim-sys:make-process
	     #'(lambda ()
		 (push (clim-sys:process-state (clim-sys:current-process)) *b*)
		 (clim-sys:process-wait
		  "enough length"
		  #'(lambda ()
		      (> (length (clim-sys:with-lock-held (*a-lock*) *a*)) 3)))
		 (push :end *b*)
		 (push (clim-sys:process-state (clim-sys:current-process)) *b*)
		 (sleep 666)
		 (push :end-end *b*))
	     :name "process 2")))
    (loop for i below 10 do (progn (print (clim-sys:process-whostate p2)) (sleep 0.5)))
    (print *b*)
    (clim-sys:process-wait "wait for end"
			   #'(lambda () (find :end *b*)))
    (print 9)
    (clim-sys:destroy-process p1)
    (clim-sys:destroy-process p2)
    (print *a*)
    (print *b*)))

(import 'clim-sys:with-recursive-lock-held)

(defun test-interrupt ()
  (let ((p1 (clim-sys:make-process #'(lambda () (loop
						   (with-recursive-lock-held (*a-lock*)
						     (push (get-universal-time) *a*))
						   (sleep 1)
						   (if (> (length (with-recursive-lock-held (*a-lock*) *a*)) 2)
						       (clim-sys:process-interrupt (clim-sys:current-process) #'(lambda ()
														  (with-recursive-lock-held (*a-lock*)
														    (push "biu" *a*))
														  (sleep 6))))
						   (if (> (length (with-recursive-lock-held (*a-lock*) *a*)) 4)
						       (return))
						   (with-recursive-lock-held (*a-lock*)
						     (push (clim-sys:process-name (clim-sys:current-process)) *a*))
						   (sleep 1)))
				   :name "daye process")))
    (loop (with-recursive-lock-held (*a-lock*)
	    (print *a*))
       (sleep 0.5)
       (with-recursive-lock-held (*a-lock*)
	 (if (> (length *a*) 4)
	     (return))))
    (print *a*)))

(defun test-disable-enable ()
  (let ((p1 (clim-sys:make-process #'(lambda ()
				       (let ((i 1))
					 (loop
					    (push i *a*)
					    (sleep 1)
					    (incf i))))
				   :name "hehe")))
    (print *a*)
    (sleep 3)
    
    (clim-sys:disable-process p1)
    (print (clim-sys:process-state p1))
    (print *a*)

    (sleep 3)
    (print *a*)

    (clim-sys:enable-process p1)
    (print (clim-sys:process-state p1))
    (sleep 3)
    (print *a*)

    (sleep 3)
    (print *a*)
    (clim-sys:restart-process p1)

    (sleep 3)
    (print *a*)

    (clim-sys:destroy-process p1)))

(defun test-no-scheduling ()
  (let ((p1 (clim-sys:make-process #'(lambda ()
				       (clim-sys:without-scheduling
					 (let ((i 1))
					   (loop
					      (push i *a*)
					      (sleep 1)
					      (incf i)))))
				   :name "hehe")))
    (print *a*)
    (sleep 3)
    
    (clim-sys:disable-process p1)
    (print (clim-sys:process-state p1))
    (print *a*)

    (sleep 3)
    (print *a*)

    (clim-sys:enable-process p1)
    (print (clim-sys:process-state p1))
    (sleep 3)
    (print *a*)

    (sleep 3)
    (print *a*)
    (clim-sys:restart-process p1)

    (sleep 3)
    (print *a*)

    (clim-sys:destroy-process p1)))

```

**Comment by dkochmanski** [comment]
generally this stub implementation is provided for backward compatibility, we encourage using bordeaux-threads. For more elaborate functionality you may be interested in:

https://gitlab.common-lisp.net/dkochmanski/ugly-processes

**Comment by dkochmanski** [comment]
Having that in mind, do you think we should move forward with the code review? I mean - do you have specific need which can't be achieved with `bordeaux-threads`?

**Comment by ailisp** [comment]
great, i haven't seen the ugly-processes project

2016年10月1日 下午3:58，"Daniel Kochmanski" <notifications@github.com>写道：

**Comment by dkochmanski** [comment]
so it's OK to close this PR? (I know you spent some time on it, sorry about that)

**Comment by ailisp** [comment]
OK. Thank you. I learn a lot from your implementation and from some
books.when try to get all these correct, so it doesn't matter. Maybe we can
implement without-scheduling in ugly-processes? It can't stop all
interruptions, but interruption by ugly-processes' calls are guaranteed to
be avoided.

**Comment by dkochmanski** [comment]
sure, why not. Basically the main blocker from the public announcement of ugly-processes is lack of tests and documentation.

**Pull request closed without merging**
