### PR TITLE
Add a new README

### PR DESCRIPTION
**Pull request by nsrahmad**
Plus a minor update to `dragndrop` example.

### CODE REVIEW

**Comment by nsrahmad** [comment]
You can see it live on my fork [here](https://github.com/nsrahmad/McCLIM).

**Comment by dkochmanski** [comment]
Looks like an improvement, but I have a few remarks:
- it is McCLIM, not McClim
- Iteration-X is just for numbering reports for the community, I wouldn't put it in the readme
`McCLIM 0.9.7-dev post-"St. George's Day"` for now is fine, soon we will release `McCLIM 0.9.8 "Kupala Night"` (the biggest offender now is CLX bug on CCL)
- I would move important links near the top
- all sections should be level-3 headers starting with the first one named `Overview`
- image at the top is fine

**Comment by nsrahmad** [comment]
Thanks for review,
Evolution takes its time; with enough use CLIM will eventually be just Clim. Meanwhile I have replaced `McClim` with `McCLIM`. 
I will keep links at the bottom though. README is for someone looking at the repo (or tarball) for the first time. they will definitely want to see what McCLIM is about before going for further details.

**Comment by dkochmanski** [comment]
you have missed second paragraph (it is `McCLim`) and `Subdirectory overview` -> `Extensions` – similar typo. Except that looks fine to me.

**Comment by nsrahmad** [comment]
Thanks again. I was trying to update from phone. I have updated it and merged all updates into a single commit.

**Comment by dkochmanski** [comment]
I've added one small commit on top of this. Merging now, thanks!

**Pull request merged**
